reserved = {
  'if': 'IF',
  'else': 'ELSE',
  'for': 'FOR',
  'true': 'TRUE',
  'false': 'FALSE',
  'struct':'STRUCT',
  'switch':'SWITCH',
  'break':'BREAK',
  'case':'CASE',
  'const':'CONST',
  'continue':'CONTINUE',
  'default':'DEFAULT',
  'func':'FUNC',
  'import':'IMPORT',
  'inteface':'INTERFACE',
  'map':'MAP',
  'range':'RANGE',
  'return':'return',
  'type':'TYPE',
  'var':'VAR',
  'package':'PACKAGE',
  'int':'INT',
  'int16':'INT16',
  'int32':'INT32',
  'int64':'INT64',
  'uint':'UINT',
  'uint16':'UINT16',
  'uint32':'UINT32',
  'uint64':'UINT64',
  'bool':'BOOL',
  'float32':'FLOAT32',
  'float64':'FLOAT64',
  'complex64':'COMPLEX64',
  'complex128':'COMPLEX128',
  'string':'STRING',
  'Println':'PRINTLN'
}
